
import "./globals.css";
import Header from "@/Components/Header";
import AppProvider from "@/redux/provider";
import MainLayout from "@/layouts/MianLayout";



export const metadata = {
  title: "Binod silwal Portfolio",
  description: "Generated by create next app",
  keywords:
    "trekking guides, trekking routes, hiking trails, backpacking tips, wilderness adventures, outdoor enthusiasts, adventure seekers, wilderness lovers, backpacking and trekking",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className="bg-gray-100 dark:bg-red-900">
      <body >
        
        <AppProvider>
          <MainLayout>
            <Header />
            { children }
           
          </MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
